services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./local-data/db/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
      - ./local-data/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - api-net
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./local-data/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - api-net
  cache:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./local-data/cache/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - api-net
networks:
  api-net:
    driver: bridge